# Generated by Django 5.2.4 on 2025-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Koppee', '0002_login_remove_blogpost_author_remove_review_coffee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
